### ISSUE TITLE
Bug: Doesn't work with flatpak obsidian :(

### ISSUE THREAD

**Issue by alexivlao** [aqav/obsidian-canvas-links#3]
**Describe the bug**
After manual installation, the plugin is displayed in the list of community plugins, but when it is enabled, an error occurs.
![Снимок экрана_2023-06-08_15-15-41](https://github.com/aqav/obsidian-canvas-view/assets/111527277/940645e0-66bb-4fb8-96a1-9eadd727558d)

**Step to reproduce**
I moved the `main.ts`, `styles.css`, `manifest.json` files to `/.obsidian/plugins/obsidian-canvas-view`, tried renaming `main.ts` to `main.js` and transfer all cloned files but still doesn't work.

**Expected behavivor**
Work after enabling plugin in community plugins tab

**Additional information**
Flatpack obsidian is maintained by the flatpack community, so it's possible that the problem is only with my version of the program and maybe I should just wait until your plugin appears in the community plugin list, but I decided to leave this report anyway. Xubuntu 22.04.2 LTS 

Sorry for any mistakes in creating an issue, this is my first time using github...

**Comment by aqav** [comment]
Hi @alexivlao 

I think the problem is due to some of your wrong step

you should download the `main.js`(not `main.ts` from the source code), `styles.css`, `manifest.json` from [the latest release](https://github.com/aqav/obsidian-canvas-view/releases), then put them into `/.obsidian/plugins/obsidian-canvas-view`.

If you prefer to install manually, you can git clone the source code into `/.obsidian/plugins/obsidian-canvas-view` and run `npm install`, `npm run dev` in the same dir.

Have a try :)

**Comment by aqav** [comment]
Renaming the `main.ts` to `main.js` is not work, the javascript file should generate from typescript file by `npm`
