### ISSUE TITLE
[FR] Display the canvas where the file is located when selecting it in Canvas.

### ISSUE THREAD

**Issue by wwjCMP** [aqav/obsidian-canvas-links#9]
In the official outbound and inbound linking functions, we can retrieve the outbound and inbound links by selecting files in the canvas. However, this plugin cannot handle similar situations.

**Comment by aqav** [comment]
The plugin designed to show what files contained in the current active canva and what canvas contain the current active file. click different note in canvas for showing the outgoing links and backlinks of the note is leaved to the offcial function to achive

BTW, implement all capabilities of official link function to this plugin is hard, and I have no clue how to do this because some limits of [Obsidian-API](https://github.com/obsidianmd/obsidian-api)

Usually you should use the official function and this plugin both
